fix pycodestyle

diff --git a/0x01-python-if_else_loops_functions/viay b/0x01-python-if_else_loops_functions/viay
--- a/0x01-python-if_else_loops_functions/viay
+++ b/0x01-python-if_else_loops_functions/viay
@@ -10,8 +10,19 @@ fi
 xset -q | grep "Caps Lock:   on" && xdotool key Caps_Lock
 
 # open vi with the provided filename
-vi "$1"
+vi "+set nu" "$1"
 
 # turn off caps lock again
 xset -q | grep "Caps Lock:   on" && xdotool key Caps_Lock
+
+# ask if file should be checked using pycodestyle
+read -p "Do you want to check the file using pycodestyle? (y/n) " check
+
+if [ "$check" == "y" ] || [ "$check" == "Y" ]; then
+  # run pycodestyle
+  if ! pycodestyle "$1"; then
+    echo "pycodestyle check failed for file: $1"
+    exit 1
+  fi
+fi
 
